development:
  aws_access_key_id: 'AKIAJ7EH5OFSFNYHXQWA'
  aws_secret_access_key: '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'
  provider: 'AWS'

test:
  aws_access_key_id: 'AKIAJ7EH5OFSFNYHXQWA'
  aws_secret_access_key: 'telddndfoU6/sh7qFtQILH9eK+ouN8HXgLRLUq3m'
  provider: 'AWS'

# set these environment variables on your prod server
production:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  provider: 'AWS'
