development:
  sessions:
    default:
      database: pushly_store_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: pushly_store_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
