development:
  sessions:
    default:
      database: theme_my_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: pushly_store_test
      hosts:
        - localhost:27017
